### ISSUE TITLE
Remote agent not working

### ISSUE THREAD

**Issue by alexandrasandulescu** [ITEA3-Measure/MeasurePlatform#13]
After following the instructions [1], the remote measure is not visible in Platform Agents page. Agent log is:
2017-09-12 15:39:52.482 ERROR 22331 --- [taskScheduler-1] o.m.p.a.r.impl.MeasureCatalogueService   : null
http://x.x.x.x:8444/api/remote-measure/execution-list

On the platform side, I printed some data:
Id: AABAgent
org.measure.smm.remote.RemoteMeasureInstanceList@3e8ea148
org.measure.smm.remote.RemoteMeasureInstanceList@3e8ea148

the application.properties file is:
measure.repository.path=/data/MeasurePlatform
measure.server.adress=x.x.x.x:8444
measure.agent.name=AABAgent

[1] https://github.com/ITEA3-Measure/MeasurePlatform/wiki/Client-Side-Measure#start-agent

**Comment by aabherve** [comment]
I try with the last release [1] Agents which communicate with the Test platform and it' work.

Configuration : 
measure.repository.path=C:/Users/aabherve/Desktop/MeasureAgent/storage/
measure.server.adress=194.2.241.244/measure
measure.agent.name=AgentA

The "measure.repository.path" directory contained your measures ?
Your server is runing on port 8444 ?
Are you shure that the measure that you try to publish is correct ?

[1] https://github.com/ITEA3-Measure/MeasureAgent/releases/download/v0.5.00/MeasureAgent.zip

**Comment by alexandrasandulescu** [comment]
@aabherve, 
Yes, I changed the default port because we have other services running on the same server.
The measure is taken from Measures repository. 
It looks like the storage path was wrong.

I fixed the storage path and now I get the following error:

2017-09-12 17:15:58.703  INFO 24759 --- [taskScheduler-1] o.m.p.a.s.PlatformRegistrator            : Registration : ClassComplexity_SonarCube4.5 (AABAgent) http://x.x.x.x:8444/api/remote-measure/registration
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.put(RestTemplate.java:432)
	at org.measure.platform.agent.serviceregistrator.PlatformRegistrator.registerMeasures(PlatformRegistrator.java:60)
	at org.measure.platform.agent.serviceregistrator.PlatformRegistrator.reportCurrentTime(PlatformRegistrator.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aabherve** [comment]
Ok, ther is an issue with the version of the Agent and version of the MeasurePlatform.
Did you used a Released version of the MeasurePlatform and of the Agent ? or did you run the platform form source ?

I think that there is an issue with the the  v0.5.0.2 release. The code source (tag) associate with this release is more recent than the code of the application which has bean packaged. ( It's the reason why the version of SMMMeasureAPI  library used in the code source  is 0.4 and not 0.2.08).

Could you retry your tests using the package version of the platform or source code form this tag [1] ?
[1] https://github.com/ITEA3-Measure/MeasurePlatform/tree/5f26678b652d8cc48e006038d09c65073394f726

**Comment by alexandrasandulescu** [comment]
it works with the source code from this tag [1].
thanks

[1] https://github.com/ITEA3-Measure/MeasurePlatform/tree/5f26678b652d8cc48e006038d09c65073394f726

**Comment by aabherve** [comment]
i will try to fix the release
